<?php
//users
$this->addRoute('User/register','User,register');
$this->addRoute('User/login','User,login');
//customers
$this->addRoute('Customer/update','Customer,update');
$this->addRoute('Customer/logout','Customer,logout');
$this->addRoute('Customer/checkout','Customer,checkout');
$this->addRoute('Customer/deactivate','Customer,deactivate');
$this->addRoute('Customer/home','Customer,index');
$this->addRoute('Customer/dashboard','Customer,dashboard');
//products
$this->addRoute('Product/listing','Product,listings');
$this->addRoute('Product/index','Product,description');
$this->addRoute('Product/search','Product,search');
$this->addRoute('Product/search','Product,search');
$this->addRoute('Product/addCart','Product,addToCart');
$this->addRoute('Product/view','Product,viewCart');
$this->addRoute('Product/removeCart','Product,removeFromCart');
$this->addRoute('Product/eyeglasses','Product,listingFliter');
//admins
$this->addRoute('Admin/index','Admin,index');
$this->addRoute('Admin/modify','Admin,modify');
$this->addRoute('Admin/create','Admin,create');
$this->addRoute('Admin/productListing','Admin,listings');
$this->addRoute('Admin/customerList','Admin,customerList');
$this->addRoute('Admin/disableCustomer','Admin,deactivate');
//wishlist
$this->addRoute('Wishlist/add','Wishlist,addToWishlist');
$this->addRoute('Wishlist/remove','Wishlist,removeFromWishlist');
$this->addRoute('Wishlist/displaytest','Wishlist,displayWishlist');
//ticket
$this->addRoute('Ticket/create','Ticket,createTicket');
$this->addRoute('Ticket/ongoing','Ticket,currentTickets');
$this->addRoute('Ticket/index','Ticket,description');
//review
$this->addRoute('Review/create','Review,create');
//misc
$this->addRoute('contact','User,contact');

