<?php
$this->addRoute('User/register','User,register');
$this->addRoute('User/login','User,login');
$this->addRoute('Customer/update','Customer,update');
$this->addRoute('Customer/logout','Customer,logout');
$this->addRoute('contact','User,contact');
$this->addRoute('Product/listing','Product,listings');
$this->addRoute('Product/index','Product,description');
$this->addRoute('Product/search','Product,search');
$this->addRoute('Product/search','Product,search');
$this->addRoute('Admin/index','Admin,index');
$this->addRoute('Admin/modify','Admin,modify');
$this->addRoute('Admin/create','Admin,create');
$this->addRoute('Admin/productListing','Admin,listings');
$this->addRoute('Customer/Checkout','Customer,checkout');
